// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use goa_sys;
use std::fmt;

glib_wrapper! {
    pub struct Chat(Interface<goa_sys::GoaChat>);

    match fn {
        get_type => || goa_sys::goa_chat_get_type(),
    }
}

impl Chat {
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call goa_sys:goa_chat_interface_info() }
    //}

    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call goa_sys:goa_chat_override_properties() }
    //}
}

pub const NONE_CHAT: Option<&Chat> = None;

pub trait ChatExt: 'static {}

impl<O: IsA<Chat>> ChatExt for O {}

impl fmt::Display for Chat {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Chat")
    }
}
