// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use goa_sys;
use std::fmt;

glib_wrapper! {
    pub struct Maps(Interface<goa_sys::GoaMaps>);

    match fn {
        get_type => || goa_sys::goa_maps_get_type(),
    }
}

impl Maps {
    //#[cfg(any(feature = "v3_14", feature = "dox"))]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call goa_sys:goa_maps_interface_info() }
    //}

    //#[cfg(any(feature = "v3_14", feature = "dox"))]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call goa_sys:goa_maps_override_properties() }
    //}
}

pub const NONE_MAPS: Option<&Maps> = None;

pub trait MapsExt: 'static {}

impl<O: IsA<Maps>> MapsExt for O {}

impl fmt::Display for Maps {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Maps")
    }
}
