// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod account;
pub use self::account::{Account, NONE_ACCOUNT};
pub use self::account::AccountExt;

#[cfg(any(feature = "v3_8", feature = "dox"))]
mod calendar;
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::calendar::{Calendar, NONE_CALENDAR};
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::calendar::CalendarExt;

mod chat;
pub use self::chat::{Chat, NONE_CHAT};
pub use self::chat::ChatExt;

mod client;
pub use self::client::{Client, ClientClass, NONE_CLIENT};
pub use self::client::ClientExt;

#[cfg(any(feature = "v3_8", feature = "dox"))]
mod contacts;
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::contacts::{Contacts, NONE_CONTACTS};
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::contacts::ContactsExt;

mod documents;
pub use self::documents::{Documents, NONE_DOCUMENTS};
pub use self::documents::DocumentsExt;

#[cfg(any(feature = "v3_6", feature = "dox"))]
mod exchange;
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::exchange::{Exchange, NONE_EXCHANGE};
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::exchange::ExchangeExt;

#[cfg(any(feature = "v3_8", feature = "dox"))]
mod files;
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::files::{Files, NONE_FILES};
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::files::FilesExt;

mod mail;
pub use self::mail::{Mail, NONE_MAIL};
pub use self::mail::MailExt;

mod manager;
pub use self::manager::{Manager, NONE_MANAGER};
pub use self::manager::ManagerExt;

#[cfg(any(feature = "v3_14", feature = "dox"))]
mod maps;
#[cfg(any(feature = "v3_14", feature = "dox"))]
pub use self::maps::{Maps, NONE_MAPS};
#[cfg(any(feature = "v3_14", feature = "dox"))]
pub use self::maps::MapsExt;

#[cfg(any(feature = "v3_14", feature = "dox"))]
mod media_server;
#[cfg(any(feature = "v3_14", feature = "dox"))]
pub use self::media_server::{MediaServer, NONE_MEDIA_SERVER};
#[cfg(any(feature = "v3_14", feature = "dox"))]
pub use self::media_server::MediaServerExt;

#[cfg(any(feature = "v3_18", feature = "dox"))]
mod music;
#[cfg(any(feature = "v3_18", feature = "dox"))]
pub use self::music::{Music, NONE_MUSIC};
#[cfg(any(feature = "v3_18", feature = "dox"))]
pub use self::music::MusicExt;

mod oauth2_based;
pub use self::oauth2_based::{OAuth2Based, NONE_OAUTH2_BASED};
pub use self::oauth2_based::OAuth2BasedExt;

mod oauth_based;
pub use self::oauth_based::{OAuthBased, NONE_OAUTH_BASED};
pub use self::oauth_based::OAuthBasedExt;

mod object;
pub use self::object::{Object, NONE_OBJECT};
pub use self::object::ObjectExt;

mod object_manager_client;
pub use self::object_manager_client::{ObjectManagerClient, ObjectManagerClientClass, NONE_OBJECT_MANAGER_CLIENT};

#[cfg(any(feature = "v3_6", feature = "dox"))]
mod password_based;
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::password_based::{PasswordBased, NONE_PASSWORD_BASED};
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::password_based::PasswordBasedExt;

#[cfg(any(feature = "v3_8", feature = "dox"))]
mod photos;
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::photos::{Photos, NONE_PHOTOS};
#[cfg(any(feature = "v3_8", feature = "dox"))]
pub use self::photos::PhotosExt;

#[cfg(any(feature = "v3_12", feature = "dox"))]
mod printers;
#[cfg(any(feature = "v3_12", feature = "dox"))]
pub use self::printers::{Printers, NONE_PRINTERS};
#[cfg(any(feature = "v3_12", feature = "dox"))]
pub use self::printers::PrintersExt;

#[cfg(any(feature = "v3_12", feature = "dox"))]
mod read_later;
#[cfg(any(feature = "v3_12", feature = "dox"))]
pub use self::read_later::{ReadLater, NONE_READ_LATER};
#[cfg(any(feature = "v3_12", feature = "dox"))]
pub use self::read_later::ReadLaterExt;

#[cfg(any(feature = "v3_6", feature = "dox"))]
mod ticketing;
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::ticketing::{Ticketing, NONE_TICKETING};
#[cfg(any(feature = "v3_6", feature = "dox"))]
pub use self::ticketing::TicketingExt;

#[cfg(any(feature = "v3_26", feature = "dox"))]
mod todo;
#[cfg(any(feature = "v3_26", feature = "dox"))]
pub use self::todo::{Todo, NONE_TODO};
#[cfg(any(feature = "v3_26", feature = "dox"))]
pub use self::todo::TodoExt;

mod enums;
pub use self::enums::Error;

#[doc(hidden)]
pub mod traits {
    pub use super::AccountExt;
    #[cfg(any(feature = "v3_8", feature = "dox"))]
    pub use super::CalendarExt;
    pub use super::ChatExt;
    pub use super::ClientExt;
    #[cfg(any(feature = "v3_8", feature = "dox"))]
    pub use super::ContactsExt;
    pub use super::DocumentsExt;
    #[cfg(any(feature = "v3_6", feature = "dox"))]
    pub use super::ExchangeExt;
    #[cfg(any(feature = "v3_8", feature = "dox"))]
    pub use super::FilesExt;
    pub use super::MailExt;
    pub use super::ManagerExt;
    #[cfg(any(feature = "v3_14", feature = "dox"))]
    pub use super::MapsExt;
    #[cfg(any(feature = "v3_14", feature = "dox"))]
    pub use super::MediaServerExt;
    #[cfg(any(feature = "v3_18", feature = "dox"))]
    pub use super::MusicExt;
    pub use super::OAuth2BasedExt;
    pub use super::OAuthBasedExt;
    pub use super::ObjectExt;
    #[cfg(any(feature = "v3_6", feature = "dox"))]
    pub use super::PasswordBasedExt;
    #[cfg(any(feature = "v3_8", feature = "dox"))]
    pub use super::PhotosExt;
    #[cfg(any(feature = "v3_12", feature = "dox"))]
    pub use super::PrintersExt;
    #[cfg(any(feature = "v3_12", feature = "dox"))]
    pub use super::ReadLaterExt;
    #[cfg(any(feature = "v3_6", feature = "dox"))]
    pub use super::TicketingExt;
    #[cfg(any(feature = "v3_26", feature = "dox"))]
    pub use super::TodoExt;
}
