// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use goa_sys;
use std::fmt;

glib_wrapper! {
    pub struct Photos(Interface<goa_sys::GoaPhotos>);

    match fn {
        get_type => || goa_sys::goa_photos_get_type(),
    }
}

impl Photos {
    //#[cfg(any(feature = "v3_8", feature = "dox"))]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call goa_sys:goa_photos_interface_info() }
    //}

    //#[cfg(any(feature = "v3_8", feature = "dox"))]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call goa_sys:goa_photos_override_properties() }
    //}
}

pub const NONE_PHOTOS: Option<&Photos> = None;

pub trait PhotosExt: 'static {}

impl<O: IsA<Photos>> PhotosExt for O {}

impl fmt::Display for Photos {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Photos")
    }
}
