// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use goa_sys;
use std::fmt;

glib_wrapper! {
    pub struct Printers(Interface<goa_sys::GoaPrinters>);

    match fn {
        get_type => || goa_sys::goa_printers_get_type(),
    }
}

impl Printers {
    //#[cfg(any(feature = "v3_12", feature = "dox"))]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call goa_sys:goa_printers_interface_info() }
    //}

    //#[cfg(any(feature = "v3_12", feature = "dox"))]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call goa_sys:goa_printers_override_properties() }
    //}
}

pub const NONE_PRINTERS: Option<&Printers> = None;

pub trait PrintersExt: 'static {}

impl<O: IsA<Printers>> PrintersExt for O {}

impl fmt::Display for Printers {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "Printers")
    }
}
