// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::object::IsA;
use glib::translate::*;
use goa_sys;
use std::fmt;

glib_wrapper! {
    pub struct ReadLater(Interface<goa_sys::GoaReadLater>);

    match fn {
        get_type => || goa_sys::goa_read_later_get_type(),
    }
}

impl ReadLater {
    //#[cfg(any(feature = "v3_12", feature = "dox"))]
    //pub fn interface_info() -> /*Ignored*/Option<gio::DBusInterfaceInfo> {
    //    unsafe { TODO: call goa_sys:goa_read_later_interface_info() }
    //}

    //#[cfg(any(feature = "v3_12", feature = "dox"))]
    //pub fn override_properties(klass: /*Ignored*/&mut glib::ObjectClass, property_id_begin: u32) -> u32 {
    //    unsafe { TODO: call goa_sys:goa_read_later_override_properties() }
    //}
}

pub const NONE_READ_LATER: Option<&ReadLater> = None;

pub trait ReadLaterExt: 'static {}

impl<O: IsA<ReadLater>> ReadLaterExt for O {}

impl fmt::Display for ReadLater {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "ReadLater")
    }
}
